### ISSUE TITLE
Actually Upload an Image?

### ISSUE THREAD

**Issue by osseonews** [dashpilot/quickstart-netlify-spaces#1]
Thanks for creating this. It's very useful. Question I have is that your code only allows for a json file to be uploaded. 
```
 let data = {
                title: "Hello world. This is some text.",
            };
```

How do we define this so we can upload an image? I know in our save.js file you have option for this, but how do we send a file to that action?

**Comment by dashpilot** [comment]
Thanks for your interest! I'm still actively working on it, so I haven't made a demo for all of the features yet. I'll work on a demo for the image upload a.s.a.p, and let you know. Are you using it with Spaces or S3?

**Comment by osseonews** [comment]
Thanks for the quick response! We are using Spaces. Yes, code for image would be great. Also, actually, we are trying to upload a PDF using PDFKit + Spaces.  We were trying to use something like this: https://stackoverflow.com/questions/52723579/uploading-pdfkit-pdf-stream-to-s3-bucket-from-lambda-function-gives-error-canno  - but with no luck.

**Comment by dashpilot** [comment]
I've now added an image upload and resize example in the demo (you can set the max dimensions in the example code). Let me know if this works for you

**Comment by osseonews** [comment]
Yes, this is fantastic. Thanks so much!  If you have any clue on how to integrate PDFKit for PDF's (or some other PDF creator) that would be great. It would be similar to the JSON functionality. Type in some text into a text box in a form, and then a PDF is created and uploaded to Spaces based on the text you entered. So instead of a Json file, a pdf file is created.

**Comment by dashpilot** [comment]
PDF generation is currently outside of the scope of this project, but something like this should *theoretically* work:

```
let pdf = new PDFDocument();
pdf.text("The text for your PDF");
pdf.end();

var params = {
   Key: filename,
   Body: pdf,
   Bucket: process.env.S3_BUCKET,
   ContentType: "application/pdf",
};
```
Closing this now as the original issue has been fixed, but feel free to open a new issue or contact me directly

**Comment by osseonews** [comment]
thanks. How do we contact you directly?

**Comment by dashpilot** [comment]
DM me on https://twitter.com/dashpilot1
